// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIsRnLCRENPKHhCuN3YNIcNob5QST-R4E',
    appId: '1:979081234462:web:3655811b56d5455785c60f',
    messagingSenderId: '979081234462',
    projectId: 'smartqueue-aef3f',
    authDomain: 'smartqueue-aef3f.firebaseapp.com',
    storageBucket: 'smartqueue-aef3f.firebasestorage.app',
    measurementId: 'G-J0MGYRY83M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbkWs3N86A17AeIlPMRmT6pMtneLByLw',
    appId: '1:979081234462:android:6781aa70a595094285c60f',
    messagingSenderId: '979081234462',
    projectId: 'smartqueue-aef3f',
    storageBucket: 'smartqueue-aef3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwRaya95BtW4r1zvQzHodBb8gpW5To60',
    appId: '1:979081234462:ios:76058a1fb88afecd85c60f',
    messagingSenderId: '979081234462',
    projectId: 'smartqueue-aef3f',
    storageBucket: 'smartqueue-aef3f.firebasestorage.app',
    iosBundleId: 'com.example.smartQueueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwRaya95BtW4r1zvQzHodBb8gpW5To60',
    appId: '1:979081234462:ios:76058a1fb88afecd85c60f',
    messagingSenderId: '979081234462',
    projectId: 'smartqueue-aef3f',
    storageBucket: 'smartqueue-aef3f.firebasestorage.app',
    iosBundleId: 'com.example.smartQueueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIsRnLCRENPKHhCuN3YNIcNob5QST-R4E',
    appId: '1:979081234462:web:1c959944bb18616185c60f',
    messagingSenderId: '979081234462',
    projectId: 'smartqueue-aef3f',
    authDomain: 'smartqueue-aef3f.firebaseapp.com',
    storageBucket: 'smartqueue-aef3f.firebasestorage.app',
    measurementId: 'G-2VW1XDRK7X',
  );
}
